# schema.yaml
# Database Schema for Geo-Fenced Security Behavior Monitoring System

database:
  name: "users"
  collection: "rawdata"
  description: "Raw behavior data for user activity monitoring in geo-fenced zones"

schema_version: "1.0"
created_date: "2025-01-30"
last_updated: "2025-01-30"

dataset_schema:
  description: |
    Schema for user behavior dataset used in anomaly detection.
    Each record represents a user's environmental and behavioral state at a specific timestamp.

  fields:
    _id:
      type: integer
      description: Unique identifier for each record (auto-incremented or assigned)
      required: true

    user_id:
      type: string
      description: Unique user identifier (e.g., 'USER001', 'USER002')
      required: true

    timestamp:
      type: ISODate
      description: Timestamp of the recorded data
      format: ISO8601
      example: "2025-08-20T02:17:18.456Z"
      required: true

    temperature:
      type: integer
      description: Temperature value at the time of recording
      range: [-50, 60]
      example: 13
      required: true

    day_of_week:
      type: integer
      description: Day of the week represented numerically (0 = Sunday, 6 = Saturday)
      range: [0, 6]
      required: true

    time_of_the_day:
      type: categorical
      description: Time period of the day
      allowed_values: ["morning", "afternoon", "evening", "night"]
      required: true

    weather_conditions:
      type: categorical
      description: Weather condition at the given timestamp
      allowed_values: ["snowy", "rainy", "cloudy", "sunny"]
      required: true

    frequency_crossing:
      type: integer
      description: frequency_crossing value related to user's activity (e.g., signal or motion)
      range: [0, 1000]
      required: true

    behaviour:
      type: categorical
      description: User's behavioral status
      allowed_values: ["normal", "anomalous"]
      required: true

  metadata:
    total_features: 8
    primary_key: "_id"
    missing_values_allowed: false
    target_variable: "behaviour"
    categorical_features: ["time_of_the_day", "weather_conditions", "behaviour"]
    numerical_features: ["_id", "temperature", "frequency_crossing", "day_of_week"]
    timestamp_field: "timestamp"
    identifier_fields: ["user_id"]